[package]
name = "dcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
docker-api = "0.9.1"
tokio = { version = "1", features = ["full"] }
