name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: cargo fmt && git diff --exit-code

  build:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose

  e2e-docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run e2e tests with docker tests
        run: cargo test --verbose

  e2e-podman:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run podman tests
        run: |
          sudo systemctl stop docker
          sudo systemctl stop docker.socket
          echo "podman info"
          podman info
          systemctl --user enable --now podman.socket
          cargo test --verbose


